routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

 ////group users & posts
Route::group(['prefix'=>'admin'],function (){
    Route::resource('users','UserController');
    Route::resource('posts','PostController',['except'=>['destroy']]);
});


 ////use ajax to delete posts
//Route::get('admin/posts/delete/{id}','PostController@delete');
Route::delete('admin/posts/delete/{id}','PostController@delete');

 ////users
//Route::resource('admin/users','UserController',['as'=>'admin','only'=>['index','create','store','show','update','destroy','edit']]);
//Route::resource('admin/users','UserController', ['as'=>'admin','except'=>['show']]);

//// posts
//Route::resource('admin/posts','PostController',['as'=>'admin','only'=>['index','create','store','show','update','destroy','edit']]);
//Route::resource('admin/posts', 'PostController', ['except'=>['update']]);

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    public function posts()
    {
        return $this->hasMany('App\Post','user_id','id');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\DB;

class UserController extends Controller
{
    //
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index(Request $request)
    {
        $search = $request->input('keyword');
        $orderBy = $request->input('orderBy');
        //Sap xep
        $users = User::orderBy('id','asc');
        if ($orderBy)
        {
            switch ($orderBy){

                case 'DESC-ID':
                    $users = User::orderBy('id','desc');
                    break;
                case 'ASC-ID':
                    $users = User::orderBy('id','asc');
                    break;
                case 'ASC-NAME':
                    $users = User::orderBy('name','asc');
                    break;
                case 'DESC-NAME':
                    $users = User::orderBy('name','desc');
                    break;
            }
        }
        //tim kiem
        if($search)
        {
            $users->where('name','like',"%$search%")
                ->orwhere('id','like',"%$search%");
        }
        $data['users'] = $users->paginate(5);
        $data['keyword'] = $search;
        $data['orderBy'] = $orderBy;
        return view('admin.users.index', $data);
    }

    public function create()
    {
        return view('admin.users.create');
    }

    public function store(Request $request)
    {
        $valid = Validator::make($request->all(), [
            'name' => 'required',
            'email' => 'required|email|unique:users,email',
            'password' => 'required|string|min:8|confirmed',
        ], [
            'name.required' => 'Please enter name', 'email.required' => 'Please enter email',
            'email.unique' => 'Email existed', 'email.email' => 'No must format email',
            'password.required' => 'Please enter password',
        ]);
        if ($valid->fails()) {
            return redirect()->back()->withErrors($valid)->withInput();
        } else {
            $users = User::create([
                'name' => $request->input('name'),
                'email' => $request->input('email'),
                'password' => bcrypt($request->input('password')),
            ]);

            return redirect()->route('users.index')->with('message', "Added $users->name successfully !");
        }
    }

    public function show($id)
    {
        $data['user'] = User::find($id);
        if ($data['user'] !== null) {
            return view('admin.users.edit', $data);
        }
        return redirect()->route('users.index')->with('error', "This user could not be found!");
    }
    public function edit($id)
    {
        $data['user'] = User::find($id);
        return view('admin.users.edit', $data);
    }
    public function update(Request $request, $id)
    {
        $valid = Validator::make($request->all(), [
            'name' => 'required', 'email' => 'required|email|unique:users,email,'.$id,
        ], [
            'name.required' => 'Please enter name',
            'email.required' => 'Please enter email',
            'email.unique' => 'Email existed', 'email.email' => 'No must format email',
        ]);
        if ($valid->fails()) {
            return redirect()->back()->withErrors($valid)->withInput();
        } else {
            $user = User::find($id);
            $user->name = $request->input('name');
            $user->email = $request->input('email');
            if ($request->input('password')) {
                $user->password = bcrypt($request->input('password'));
            }
            $user->save();

            return redirect()->route('users.index')->with('message', "Updated $user->name successfully !");
        }
    }

    public function destroy(User $user)
    {

        if ($user->id == Auth::user()->id)
        {
            return redirect()->route('users.index')->with('error', "You can not delete yourself !");

        }
        else {
            $user->delete();
            return redirect()->route('users.index')->with('message', "Delete $user->name successfully !");
        }
    }
}

resources/views/admin/users/create.blade.php
@extends('admin.master')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-6">
           <h3>CREATE NEW USER</h3>
        </div>
        <div class="col-md-8">
            <div>
                <a href="{{route('users.index')}}"></a>
            </div>
            <div class="panel panel-default">
                <br>
                <div class="panel-body">
                    <form action="{{route('users.store')}}" method="POST">
                        @csrf
                        <div class="form-group has-success">
                            <label for="name">Name</label>
                            <input type="text" class="form-control" id="name"  name="name" placeholder="Name" value="{{old('name')}}">
                            <span id="helpBlock2" class="help-block">{{$errors->first('name')}}</span>
                        </div>
                        <div class="form-group has-success">
                            <label for="email">Email address</label>
                            <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp" placeholder="Enter email" value="{{old('email')}}">
                            <span id="helpBlock2" class="help-block">{{$errors->first('email')}}</span>
                        </div>
                        <div class="form-group has-success">
                            <label for="password">Password</label>
                            <input type="password" class="form-control" id="password" name="password" placeholder="Password">
                            <span id="helpBlock2" class="help-block">{{$errors->first('password')}}</span>
                        </div>
                        <div class="form-group has-success">
                            <label for="password_confirmation ">Confirm Password</label>
                            <input type="password" class="form-control" id="password_confirmation" name="password_confirmation" placeholder="Password">
                        </div>
                        <button type="submit" class="btn btn-success">Create</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection



{{--FORM BOOTSTRAP--}}
{{--<button class="btn btn-dark" data-toggle="modal" data-target="#create">+ Create</button>--}}
{{--<div class="modal" tabindex="-1" role="dialog" id="create">--}}
{{--    <div class="modal-dialog" role="document">--}}
{{--        <div class="modal-content">--}}
{{--            <div class="modal-header">--}}
{{--                <h5 class="modal-title"></h5>--}}
{{--                <button type="button" class="close" data-dismiss="modal" aria-label="Close">--}}
{{--                    <span aria-hidden="true">&times;</span>--}}
{{--                </button>--}}
{{--            </div>--}}
{{--            <div class="modal-body">--}}
{{--                <div class="row">--}}
{{--                    <div class="col-md-12">--}}
{{--                        <br>--}}
{{--                        <div class="panel panel-default">--}}
{{--                            <div class="panel-heading">ADD USER</div>--}}
{{--                            <br>--}}
{{--                            <div class="panel-body">--}}
{{--                                <form action="{{route('admin.users.store')}}" method="POST">--}}
{{--                                    @csrf--}}
{{--                                    <div class="form-group has-success">--}}
{{--                                        <label for="name">Name</label>--}}
{{--                                        <input type="text" class="form-control" id="name"  name="name" placeholder="Name" value="{{old('name')}}">--}}
{{--                                        <span id="helpBlock2" class="help-block">{{$errors->first('name')}}</span>--}}
{{--                                    </div>--}}
{{--                                    <div class="form-group has-success">--}}
{{--                                        <label for="email">Email address</label>--}}
{{--                                        <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp" placeholder="Enter email" value="{{old('email')}}">--}}
{{--                                        <span id="helpBlock2" class="help-block">{{$errors->first('email')}}</span>--}}
{{--                                    </div>--}}
{{--                                    <div class="form-group has-success">--}}
{{--                                        <label for="password">Password</label>--}}
{{--                                        <input type="password" class="form-control" id="password" name="password" placeholder="Password">--}}
{{--                                        <span id="helpBlock2" class="help-block">{{$errors->first('password')}}</span>--}}
{{--                                    </div>--}}
{{--                                    <div class="form-group has-success">--}}
{{--                                        <label for="password_confirmation ">Confirm Password</label>--}}
{{--                                        <input type="password" class="form-control" id="password_confirmation " name="password_confirmation " placeholder="Password">--}}
{{--                                    </div>--}}
{{--                                    <button type="submit" class="btn btn-success">Create</button>--}}
{{--                                </form>--}}
{{--                            </div>--}}
{{--                        </div>--}}
{{--                    </div>--}}
{{--                </div>--}}
{{--            </div>--}}
{{--        </div>--}}
{{--    </div>--}}
{{--</div>--}}

resources/views/admin/users/delete.blade.php
<button class="btn btn-danger" data-toggle="modal" data-target="#delete-{{$user->id}}">Delete</button>
<div class="modal" tabindex="-1" role="dialog" id="delete-{{$user->id}}">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete {{$user->name}}?</p>
            </div>
            <form action="{{route('users.destroy',['id'=>$user->id])}}" method="POST"
                  id="user-delete-{{$user->id}}">
                {{csrf_field()}}
                {{method_field('delete')}}
                <div class="modal-footer">
                    <button type="submit" class="btn btn-danger" name="" id="">Delete</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/admin/users/edit.blade.php
@extends('admin.master')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h3>EDIT USER </h3>
            </div>
            <div class="col-md-8">
                <br>
                <div class="panel panel-default">
                    <br>
                    <div class="panel-body">
                        <form action="{{route('users.update',['id'=>$user->id])}}" method="POST" id="edit-form">
                            @csrf
                            {{method_field('put')}}
                            <div class="form-group has-success">
                                <label for="name">Name</label>
                                <input type="text" class="form-control" id="name"  name="name" placeholder="Name" value="{{$user->name}}">
                                <span id="helpBlock2" class="help-block">{{$errors->first('name')}}</span>
                            </div>
                            <div class="form-group has-success">
                                <label for="email">Email address</label>
                                <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp" placeholder="Enter email" value="{{$user->email}}">
                                <span id="helpBlock2" class="help-block">{{$errors->first('email')}}</span>
                            </div>
                            <div class="form-group has-success">
                                <label for="password">Password</label>
                                <input type="password" class="form-control" id="password" name="password" placeholder="Password">
                                <span id="helpBlock2" class="help-block">{{$errors->first('password')}}</span>
                            </div>
                            <div class="form-group has-success">
                                <label for="password_confirmation ">Confirm Password</label>
                                <input type="password" class="form-control" id="password_confirmation" name="password_confirmation" placeholder="Password">
                            </div>
                            <button type="submit" class="btn btn-success">Save changes</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/users/index.blade.php
@extends('admin.master')
@section('content')
    <div class="container">
        <div>
            {{--add new user--}}
{{--            @include('users.create')  --}}
            <a href="{{route('users.create')}}" class="btn btn-dark"> + Create</a>
            <br>
        </div>

        <br>
        <div class="row">
             {{--search--}}
            <div class="col-md-6">
                <div class="col-xs-8 col-xs-offset-2">
                    <form action="{{route('users.index')}}" method="GET">
                        @csrf
                        <div class="input-group">
                            <span class="btn btn-outline-secondary">Filter by: </span>
                            <select name="orderBy">
                                <option value="null" {{ !$orderBy?'selected':'' }}>Choose sort</option>
                                <option value="DESC-ID" {{ $orderBy == 'DESC-ID'?'selected':'' }}>DESC ID</option>
                                <option value="ASC-ID" {{ $orderBy == 'ASC-ID'?'selected':'' }}>ASC ID</option>
                                <option value="ASC-NAME" {{ $orderBy == 'ASC-NAME'?'selected':'' }} >ASC NAME</option>
                                <option value="DESC-NAME" {{ $orderBy == 'DESC-NAME'?'selected':'' }}>DESC NAME</option>
                            </select>
                            <input type="search" class="form-control" id="keyword" name="keyword" placeholder="Search name..."
                                   value="{{$keyword}}">
                            <span class="input-group-btn">
                                <button class="btn btn-primary" type="submit"><span class="fa fa-search">
                                </span>Search</button>
                            </span>
                        </div>

                    </form>
                    <br>
                </div>
            </div>

            <div class="col-md-1">
                <a href="{{route('users.index')}}" class="btn btn-dark">List users</a>
            </div>
            <div class="col-md-12">
            {{-- show list users--}}
                <br>
                <div class="panel panel-default">
                    <div class="" style="font-size: x-large;color: coral;">LIST USERS</div>
                    <br>
                    <div class="panel-body">
                        @if(session('message'))
                            <div class="alert alert-success" id="message">{{session('message')}}</div>
                        @endif
                        @if(session('error'))
                            <div class="alert alert-danger" id="error">{{session('error')}}</div>
                        @endif
                        <script language="JavaScript">
                            setTimeout(function(){$('#message').remove()},3000)
                        </script>
                        <script language="JavaScript">
                            setTimeout(function(){$('#error').remove()},3000)
                        </script>
                        <table class="table">
                            <thread>
                                <tr>
                                    <th>ID</th>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Create_at</th>
                                    <th>Update_at</th>
                                    <th>Options</th>
                                </tr>
                            </thread>
                            <tbody>
                                @forelse($users as $user)
                                    <tr>
                                        <td>{{$user->id}}</td>
                                        <td>{{$user->name}}</td>
                                        <td>{{$user->email}}</td>
                                        <td>{{$user->created_at}}</td>
                                        <td>{{$user->updated_at}}</td>
                                        <td>
                                            {{--edit--}}
{{--                                            @include('users.update')--}}
                                            <a href="{{route('users.edit',['id'=>$user->id])}}" class="btn btn-success"
                                               >Edit</a>
                                            {{--delele--}}
                                            @include('admin.users.delete')
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="5">No Data!</td>
                                    </tr>
                                @endforelse
                            </tbody>
                         
                        </table>
                        <div class="text-center">
                            {{$users->links()}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/users/update.blade.php
{{--<button class="btn btn-primary" data-toggle="modal" data-target="#edit-{{$user->id}}">Edit</button>--}}
{{--<div class="modal" tabindex="-1" role="dialog" id="edit-{{$user->id}}">--}}
{{--    <div class="modal-dialog" role="document">--}}
{{--        <div class="modal-content">--}}
{{--            <div class="modal-header">--}}
{{--                <h5 class="modal-title"></h5>--}}
{{--                <button type="button" class="close" data-dismiss="modal" aria-label="Close">--}}
{{--                    <span aria-hidden="true">&times;</span>--}}
{{--                </button>--}}
{{--            </div>--}}
{{--            <div class="modal-body">--}}
{{--                <div class="row">--}}
{{--                    <div class="col-md-12">--}}
{{--                        <br>--}}
{{--                        <div class="panel panel-default">--}}
{{--                            <div class="panel-heading">You are Updating info user give  {{$user->name}}</div>--}}
{{--                            <br>--}}
{{--                            <div class="panel-body">--}}
{{--                                <form action="{{route('admin.users.update',['id'=>$user->id])}}" method="POST">--}}
{{--                                    @csrf--}}
{{--                                    {{method_field('put')}}--}}
{{--                                    <div class="form-group has-success">--}}
{{--                                        <label for="name">Name</label>--}}
{{--                                        <input type="text" class="form-control" id="name"  name="name" placeholder="Name" value="{{$user->name}}">--}}
{{--                                        <span id="helpBlock2" class="help-block">{{$errors->first('name')}}</span>--}}
{{--                                    </div>--}}
{{--                                    <div class="form-group has-success">--}}
{{--                                        <label for="email">Email address</label>--}}
{{--                                        <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp" placeholder="Enter email" value="{{$user->email}}">--}}
{{--                                        <span id="helpBlock2" class="help-block">{{$errors->first('email')}}</span>--}}
{{--                                    </div>--}}
{{--                                    <div class="form-group has-success">--}}
{{--                                        <label for="password">Password</label>--}}
{{--                                        <input type="password" class="form-control" id="password" name="password" placeholder="Password">--}}
{{--                                        <span id="helpBlock2" class="help-block">{{$errors->first('password')}}</span>--}}
{{--                                    </div>--}}
{{--                                    <div class="form-group has-success">--}}
{{--                                        <label for="password_confirmation ">Confirm Password</label>--}}
{{--                                        <input type="password" class="form-control" id="password_confirmation " name="password_confirmation " placeholder="Password">--}}
{{--                                    </div>--}}
{{--                                    <button type="submit" class="btn btn-success">Save changes</button>--}}
{{--                                </form>--}}
{{--                            </div>--}}
{{--                        </div>--}}
{{--                    </div>--}}
{{--                </div>--}}
{{--            </div>--}}
{{--        </div>--}}
{{--    </div>--}}
{{--</div>--}}