routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

 ////group users & posts
Route::group(['prefix'=>'admin'],function (){
    Route::resource('users','UserController');
    Route::resource('posts','PostController',['except'=>['destroy']]);
});


 ////use ajax to delete posts
//Route::get('admin/posts/delete/{id}','PostController@delete');
Route::delete('admin/posts/delete/{id}','PostController@delete');

 ////users
//Route::resource('admin/users','UserController',['as'=>'admin','only'=>['index','create','store','show','update','destroy','edit']]);
//Route::resource('admin/users','UserController', ['as'=>'admin','except'=>['show']]);

//// posts
//Route::resource('admin/posts','PostController',['as'=>'admin','only'=>['index','create','store','show','update','destroy','edit']]);
//Route::resource('admin/posts', 'PostController', ['except'=>['update']]);

app/Post.php
<?php

namespace App;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $table='posts';

    protected $fillable = [
         'title', 'user_id', 'content','user_id' ,
    ];
    public function user()
    {
        return $this->belongsTo('App\User','user_id','id');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class PostController extends Controller
{
	public function __construct()
    {
        $this->middleware('auth');
    }
    public function index(Request $request)
    {
        $search = $request->input('keyword');
        $orderBy = $request->input('orderBy');

        //$posts = Post::orderBy('id','desc');

        /*dung function with() de giai quyet van de tranh query nhieu lan*/

        $posts = Post::with('user')->orderBy('id','desc');

        $user['users'] = User::orderBy('id','asc')->get();

        ////Xu ly tag selection

        if($orderBy)
        {
            $posts->where('user_id',$orderBy);
        }

        //tim kiem
        if ($search)
        {
            $posts->where(function ($query) use ($search){
              $query->where('title','like',"%$search%")
                    ->orwhere('content','like',"%$search%");
            });
        }
        $data['posts'] = $posts->paginate(5);
        $data['keyword'] = $search;
        $data['orderBy'] = $orderBy;
        return view('admin.posts.index',$data,$user);

    }

    public function create()
    {
        return view('admin.posts.create');
    }

    public function store(Request $request)
    {
        $data = Post::create([
            'title' => $request->input('title'),
            'content' => $request->input('content'),
            'user_id' => auth()->id(),
        ]);

        return redirect()->route('posts.index', $data)->with('message', "Created $data->title successfully !");
    }
    public function show($id)
    {
        $data['posts'] = Post::find($id);
        if ($data['posts'] !== null)
        {
            return view('admin.posts.edit',$data);
        }
        return redirect()->route('posts.index')->with('error','Not found !');
    }
    public function edit($id)
    {
        $data['posts'] = Post::find($id);
        return view('admin.posts.edit', $data);
    }
    public function update(Request $request , $id)
    {
        $data = Post::find($id);
        $data->title = $request->input('title');
        $data->content = $request->input('content');
        $data->save();

        return redirect()->route('posts.index',$data)->with('message','Editted seccessfully !');
    }

    //public function destroy($id)
    //{
    //    $data = Post::find($id);
    //
    //    if ($data !== null)
    //    {
    //        $data->delete($id);
    //        return redirect()->route('posts.index')->with('message', "Deleted successfully !");
    //    }
    //    return redirect()->route('posts.index')->with('error', "Not successfully !");
    //}

    public function delete($id)
    {
        $post = Post::find($id);
        //dd($post->toArray());
        if ($post->user_id == Auth::user()->id )
        {
            $post->delete();
            //return response()->json(compact('post'),'200');
            return response()->json([
                'message' => 'Delete post successfully !'
            ],'200');
        }
        return response()->json([
            'error' => 'You have not access !'
        ],'403');
    }


}

resources/views/admin/posts/create.blade.php
@extends('admin.master')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div>
                    <h3>Create new posts </h3>
                </div>
                <div class="panel panel-default">
                    <br>
                    <div class="panel-body">
                        <form action="{{route('posts.store')}}" method="POST">
                            @csrf
                            <div class="form-group has-success">
                                <label for="title">Title *</label>
                                <input type="text" class="form-control" id="title"  name="title" required="required" placeholder="title" value="{{old('title')}}">
                            </div>
                            <div class="form-group has-success">
                                <label for="content">Content *</label>
                                <textarea name="content" id="content" class="form-control" cols="30" rows="10" maxlength="65525" required="required"></textarea>
                            </div>
                            <button type="submit" class="btn btn-success">Create</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/posts/destroy.blade.php
<button class="btn btn-danger" data-toggle="modal" data-target="#delete-{{$post->id}}">
    <i class="fa fa-trash"></i>
</button>
<div class="modal" tabindex="-1" role="dialog" id="delete-{{$post->id}}">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete?</p>
            </div>
            <form action="{{route('posts.destroy',['id'=>$post->id])}}" method="POST" id="user-delete-{{$post->id}}">
                {{csrf_field()}}
                {{method_field('delete')}}
                <div class="modal-footer">
                    <button type="submit" class="btn btn-danger" name="" id="">Delete</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/admin/posts/edit.blade.php
@extends('admin.master')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div>
                    <h3>Edit new posts </h3>
                </div>
                <div class="panel panel-default">
                    <br>
                    <div class="panel-body">
                        <form action="{{route('posts.update',['id' => $posts->id])}}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="form-group has-success">
                                <label for="title">Title *</label>
                                <input type="text" class="form-control" id="title"  name="title" placeholder="title" value="{{$posts->title}}">
                            </div>
                            <div class="form-group has-success">
                                <label for="content">Content *</label>
                                <textarea name="content" id="content" class="form-control" cols="30" rows="10">{{$posts->content}}</textarea>
                            </div>
                            <button type="submit" class="btn btn-success">Save changes</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/posts/index.blade.php
@extends('admin.master')
@section('content')
    <div class="container">
        <div>
            {{--add new pos--}}
            <a href="{{route('posts.create')}}" class="btn btn-dark"> + Create</a>
            <br>
        </div>

        <br>
        <div class="row">
            <div class="col-md-8">
                <div class="col-xs-8 col-xs-offset-2">
                    <form action="{{route('posts.index')}}" method="GET">
                        @csrf
                        <div class="input-group">
                            <span class="btn btn-outline-secondary">Filter by: </span>
                            <select name="orderBy" id="orderBy">
                                <option value="">Choose by name</option>
                                @foreach($users as $user)
                                    <option value="{{$user->id}}"  name="key"
                                            {{ $orderBy == $user->id ?'selected':'' }}
                                    >{{$user->name}}</option>
                                @endforeach()
                            </select>
                            <input type="search" class="form-control" id="keyword" name="keyword" placeholder="Search title,content..."
                                   value="{{$keyword}}">
                            <span class="input-group-btn">
                                <button class="btn btn-primary" type="submit">
                                    <span class="fa fa-search"></span>
                                    Search
                                </button>
                            </span>
                        </div>

                    </form>
                    <br>
                </div>
            </div>
            <div class="col-md-12">
                <br>
                <div class="panel panel-default">
                    <div class="" style="font-size: x-large;color: coral;">LIST POSTS</div>
                    <br>
                    <div class="panel-body">
                        @if(session('message'))
                            <div class="alert alert-success" id="message">{{session('message')}}</div>
                        @endif
                        @if(session('error'))
                            <div class="alert alert-danger" id="error">{{session('error')}}</div>
                        @endif
                        <script language="JavaScript">
                            setTimeout(function(){$('#message').remove()},3000)
                        </script>
                        <script language="JavaScript">
                            setTimeout(function(){$('#error').remove()},3000)
                        </script>
                        <table class="table" id="table-data">
                            <thread>
                                <tr>
                                    <th>ID</th>
                                    <th>Title</th>
                                    <th>Content</th>
                                    <th>User_Name</th>
                                    <th>Create_at</th>
                                    <th>Update_at</th>
                                    <th>Options</th>
                                </tr>
                            </thread>
                            <tbody>
                            @forelse($posts as $post)
                                <tr id="row-{{ $post->id }}">
                                    <td>{{$post->id}}</td>
                                    <td>{{$post->title}}</td>
                                    <td>{{$post->content}}</td>
                                    <td><a href="{{route('users.edit',['id'=>$post->user_id])}}">{{$post->user->name}}</a></td>
                                    <td>{{$post->created_at}}</td>
                                    <td>{{$post->updated_at}}</td>
                                    <td>
                                        <a href="{{route('posts.edit',['id'=>$post->id])}}" class="btn btn-success"><i class="fa fa-edit"></i></a>

                                        <!--/*dung dialog bootstrap*/ -->
{{--                                        @include('admin.posts.destroy')--}}

                                        <!--/*dung window.confirm*/ -->
{{--                                        <a href="{{route('posts.destroy',['id'=>$post->id])}}" class="btn btn-danger"--}}
{{--                                        onclick="event.preventDefault();window.confirm('Are you sure ?')?--}}
{{--                                        document.getElementById('user-delete-{{$post->id}}').submit():0;"><i class="fa fa-trash"></i></a>--}}
{{--                                        <form action="{{route('posts.destroy',['id'=>$post->id])}}" method="POST" id="user-delete-{{$post->id}}">--}}
{{--                                        {{csrf_field()}}--}}
{{--                                        {{method_field('delete')}}--}}
{{--                                        </form>--}}

                                        <!--/*dung ajax de delete*/ -->
{{--                                        <button class="btn btn-danger btn-delete-post" data-id='{{ $post->id }}'  data-token="{{csrf_token()}}"><i class="fa fa-trash"></i></button>--}}
                                        <button class="btn btn-danger btn-delete-post" data-id='{{ $post->id }}' ><i class="fa fa-trash"></i></button>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="7">No Data!</td>
                                </tr>
                            @endforelse
                            </tbody>

                        </table>
                        <div class="text-center">
                            {{$posts->links()}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
         $(document).ready(function () {
           $(".btn-delete-post") .on('click',function(){
              var id = $(this).data('id');
              // var token = $(this).data('token')
              if(confirm("Are you sure you want to delete this data?")){
                 $.ajax({
                     url:"/admin/posts/delete/" + id,
                     //1// method:"GET",

                     type:"DELETE",
                     //2//type:"POST",
                     // data: {_method: 'delete', _token :token},
                     success:function ()
                     {
                         $("#row-" + id).remove();
                         alert('Deleted post successfully !');
                     },
                     error:function () {
                         alert('You have not access,please choose other !');
                     }
                 })
              }
              else {
                  return false;
              }
           });
         });
    </script>
@endsection